### ISSUE TITLE
Dependency missing ?

### ISSUE THREAD

**Issue by 123maher** [matthewbdaly/artisan-standalone#4]
i have the following error whenever i try to execute artisan
Fatal error: Uncaught Error: Class 'Illuminate\Foundation\Application' not found in D:\src\test\vendor\matthewbdaly\artisan-standalone\src\Base\Application.php:9

**Comment by matthewbdaly** [comment]
That sounds like `laravel/framework` isn't installed. This should be pulled in as a dependency of `orchestra/testbench`.

Can you check they're both installed? The only way I can think of that this could occur is if you didn't install the dev dependencies.

**Comment by 123maher** [comment]
i installed the dev dependencies but the following are not present :
orchestra/testbench
lavravel/Illuminate
i thought this package doesn't need a full laravel installation anyway

**Comment by matthewbdaly** [comment]
> i thought this package doesn't need a full laravel installation anyway

No, that's impossible. It has to pull in `laravel/framework` to have access to the various Laravel classes, and it couldn't possibly work without it. It just doesn't require `laravel/laravel`. The point of this project is to make Artisan available when building a standalone Laravel package outside of an existing Laravel application.

> i installed the dev dependencies but the following are not present:

If you're adding this to an existing Laravel package, you need to include `orchestra/testbench` as a dependency so that it will pull in `laravel/framework`. Better yet, if you're creating a new package use https://github.com/matthewbdaly/laravel-package-boilerplate as a starting point as this sets it all up for you.
